var changer = "blue";

var myView = function() {
	return ([
      m("td[class=lightG]"),
      m("td[class=lightG]"),
      m("td[class=lightG]"),
      m("td[class=lightG]"),
      m("td[class=lightG]"),
      m("td[class=lightG]"),
      m("td[class=lightG]"),
      m("td[class=lightG]"),
      m("td[class=lightG]"),
      m("td[class=lightG]"),
            m("td[class=lightG]"),
      m("td[class=lightG]"),
      m("td[class=lightG]"),
      m("td[class=lightG]"),
      m("td[class=lightG]"),
      m("td[class=lightG]"),
      m("td[class=lightG]"),
      m("td[class=lightG]"),
      m("td[class=lightG]"),
      m("td[class=lightG]"),
            m("td[class=lightG]"),
      m("td[class=lightG]"),
      m("td[class=lightG]"),
      m("td[class=lightG]"),
      m("td[class=lightG]"),
      m("td[class=lightG]"),
      m("td",{class:changer}),
      m("td[class=lightG]"),
      m("td[class=lightG]"),
      m("td[class=lightG]"),
            m("td[class=lightG]"),
      m("td[class=lightG]"),
      m("td[class=lightG]"),
      m("td[class=lightG]"),
      m("td[class=lightG]"),
      m("td[class=lightG]"),
      m("td[class=lightG]"),
      m("td[class=lightG]"),
      m("td[class=lightG]"),
      m("td[class=lightG]"),
            m("td[class=lightG]"),
      m("td[class=lightG]"),
      m("td[class=lightG]"),
      m("td[class=lightG]"),
      m("td[class=lightG]"),
      m("td[class=lightG]"),
      m("td[class=lightG]"),
      m("td[class=lightG]"),
      m("td[class=lightG]"),
      m("td[class=lightG]"),
            m("td[class=lightG]"),
      m("td[class=lightG]"),
      m("td[class=lightG]"),
      m("td[class=lightG]"),
      m("td[class=lightG]"),
      m("td[class=lightG]"),
      m("td[class=lightG]"),
      m("td[class=lightG]"),
      m("td[class=lightG]"),
      m("td[class=lightG]"),
            m("td[class=lightG]"),
      m("td[class=lightG]"),
      m("td[class=lightG]"),
      m("td[class=lightG]"),
      m("td[class=lightG]"),
      m("td[class=lightG]"),
      m("td[class=lightG]"),
      m("td[class=lightG]"),
      m("td[class=lightG]"),
      m("td[class=lightG]"),
            m("td[class=lightG]"),
      m("td[class=lightG]"),
      m("td[class=lightG]"),
      m("td[class=lightG]"),
      m("td[class=lightG]"),
      m("td[class=lightG]"),
      m("td[class=lightG]"),
      m("td[class=lightG]"),
      m("td[class=lightG]"),
      m("td[class=lightG]"),
            m("td[class=lightG]"),
      m("td[class=lightG]"),
      m("td[class=lightG]"),
      m("td[class=lightG]"),
      m("td[class=lightG]"),
      m("td[class=lightG]"),
      m("td[class=lightG]"),
      m("td[class=lightG]"),
      m("td[class=lightG]"),
      m("td[class=lightG]"),
            m("td[class=lightG]"),
      m("td[class=lightG]"),
      m("td[class=lightG]"),
      m("td[class=lightG]"),
      m("td[class=lightG]"),
      m("td[class=lightG]"),
      m("td[class=lightG]"),
      m("td[class=lightG]"),
      m("td[class=lightG]"),
      m("td[class=lightG]")
    ]);
};

m.render(document.getElementById("toInsert"), myView());

startTest();

function startTest() {
  function yourFunction(){
    (changer === "blue") ? changer = "yellow" : changer = "blue";
    m.render(document.getElementById("toInsert"), myView());
    setTimeout(yourFunction, 16);
  }     
  yourFunction();
}
